### ISSUE TITLE
TypeScript default template code creates multiple bindings after deploying to Azure Function

### ISSUE THREAD

**Issue by ZachEdwards7** [Azure/azure-functions-nodejs-library#155] opened 2023-09-30 05:03 UTC
#### Investigative information

Please provide the following:

- Timestamp: 2023-09-30T04:00:03.6033634Z
- Invocation ID: 5ac4172d-aca2-4441-80c6-fb2f4e86dc29
- Region: West US 3 

#### Repro steps

Provide the steps required to reproduce the problem:

Following the instructions here to create TypeScript function in VSCode: https://learn.microsoft.com/en-us/azure/azure-functions/create-first-function-vs-code-typescript?pivots=nodejs-model-v4  

1. [Azure Portal]: Create new Event Hub namespace and new Event Hub
2. Create new Azure Function workspace in an empty folder, using TypeScript Model V4 with EventHub Binding trigger, select newly created event hub with the automatically created "RootManageSharedAccessKey" 
3. Without modifying any of the default code, run F5 the Azure Function locally and see expected event hub items in the local output
4. Deploy the local function to Azure Function - success!
5. After deployment, look in _VSCode-Azure-Resources-Functions (read-only)-eventHubTrigger1.json_ and verify there is only 1 binding present
6. Close and re-open VSCode, look again and observe there are 2 bindings now present with the same name and properties
7. Check the Azure Function logs in Portal and observe the following error in Function Logs:
`The 'eventHubTrigger1' function is in error: Multiple bindings with name 'eventHubTrigger1' discovered. Binding names must be unique.`

#### Expected behavior

Using default/template code would have no problems with deploying to Azure. 

#### Actual behavior

It seems Az Functions is adding a duplicate binding after deployment. `The 'eventHubTrigger1' function is in error: Multiple bindings with name 'eventHubTrigger1' discovered. Binding names must be unique.`

#### Known workarounds

Nothing found 

#### Related information 

Verified pre-requisites per Model V4: https://learn.microsoft.com/en-us/azure/azure-functions/create-first-function-vs-code-typescript?pivots=nodejs-model-v4#sign-in-to-azure
![image](https://github.com/Azure/azure-functions-nodejs-library/assets/44238312/7663654c-d32f-4049-9e64-0eb78fea1a82)

Have also tried different Azure regions. If you cannot find the trace, need additional details, or want to see a live repro please ping me on Teams, alias: zaedwa@

<details>
<summary>Source</summary>

```TypeScript
import { app, InvocationContext } from "@azure/functions";

export async function eventHubTrigger1(messages: unknown | unknown[], context: InvocationContext): Promise<void> {
    if (Array.isArray(messages)) {
        context.log(`Event hub function processed ${messages.length} messages`);
        for (const message of messages) {
            context.log('Event hub message:', message);
        }
    } else {
        context.log('Event hub function processed message:', messages);
    }
}

app.eventHub('eventHubTrigger1', {
    connection: 'modifiedName_RootManageSharedAccessKey_EVENTHUB', //modified name for posting github issue
    eventHubName: 'modifiedName-function', //modified name for posting github issue
    cardinality: 'many',
    handler: eventHubTrigger1
});

```
</details>

**Comment by ejizba** [comment] 2023-10-03 18:12
Mentioned offline, but I think this error is likely the true root cause, not the "multiple bindings error":

> EventHub account connection string 'modifiedName_RootManageSharedAccessKey_EVENTHUB' does not exist.Make sure that it is a defined App Setting.,

Please try adding that app setting and let us know if the errors go away

**Comment by ejizba** [comment] 2023-10-10 21:07
Closing in favor of offline discussion. Adding the app setting fixed this particular issue

**Closed as completed by ejizba** 2023-10-10 21:07 UTC
Labels: Needs: Author Feedback
