### ISSUE TITLE
Dynamic route param values ignored for non-alpha(string) types

### ISSUE THREAD

**Issue by jwhazel** [Azure/azure-functions-nodejs-library#284] opened 2024-07-31 17:08 UTC
#### Repro steps
Create a function with dynamic route parameters that either have no constraints, or accept constraints other than `alpha`. The v4 example here will suffice: https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-http-webhook-trigger?tabs=python-v2%2Cisolated-process%2Cnodejs-v4%2Cfunctionsv2&pivots=programming-language-javascript#customize-the-http-endpoint

```
const { app } = require('@azure/functions');

app.http('httpTrigger1', {
    methods: ['GET'],
    authLevel: 'anonymous',
    route: 'products/{category:alpha}/{id:int?}',
    handler: async (request, context) => {
        const category = request.params.category;
        const id = request.params.id;

        return { body: `Category: ${category}, ID: ${id}` };
    },
});
```

#### Expected behavior

Given a route of `products/abc/123`, I expect the output to be `Category: abc, ID: 123`

#### Actual behavior

The actual output is `Category: abc, ID: undefined`

#### Related information 

* It seems there's some sort of type checking going on behind the scenes and any value that is either a Number, Null, or Boolean in javascript doesn't get captured. E.g. `products/abc/null` or `products/abc/true` also return undefined. You can dump `request.params` and see that the keys simply don't exist.
* The existence of a constraint or optional qualifier `?` doesn't seem to make a difference. I only included it above because that's a verbatim example from the documentation.
* I'm running version 4.0.5198 locally. I can confirm the same issue occurs in a production Azure environment with Node 20. I have not had the chance to test other versions of Core Tools or Node.

**Comment by ejizba** [comment] 2024-07-31 18:28
Hi @jwhazel thanks for reporting - I'm going to close as duplicate of https://github.com/Azure/azure-functions-nodejs-library/issues/285 (it was in a different repo, but I just transferred it to this repo). Please see this comment for the recommended workaround: https://github.com/Azure/azure-functions-nodejs-library/issues/285#issuecomment-2261151891

**Closed as completed by ejizba** 2024-07-31 18:28 UTC
Labels: duplicate
