### ISSUE TITLE
Function Name parameter seems confusing when providing a `HttpFunctionOptions`

### ISSUE THREAD

**Issue by aaronpowell** [Azure/azure-functions-nodejs-library#35] opened 2022-10-30 22:51 UTC
Since the _Function Name_ parameter to a HTTP Trigger registration (in v4 programming model) is used to define the route, when you provide a `HttpFunctionOptions` argument rather than a callback, it seems confusing as to why you might want to provide both a name _and_ route.

I'd prefer to be able to do the following:

```ts
// name becomes route
app.get('hello-world-1', (_, req) => ({ body: "Hello World" });

// explicit route, with name derived from route
app.get({
  route: '/hello-world-2',
  handler: (_, req) => ({ body: "Hello World" })
});

// name and route defined
app.get({
  route: '/hello-world-3',
  handler: (_, req) => ({ body: "Hello World" }),
  name: "Hello World 3
});
```

**Comment by ejizba** [comment] 2022-10-31 17:27
Closing this one as duplicate of https://github.com/Azure/azure-functions-nodejs-library/issues/17

**Closed as completed by ejizba** 2022-10-31 17:27 UTC
Labels: duplicate
