### ISSUE TITLE
Using WEBSITE_RUN_FROM_PACKAGE = URL results in 0 functions found using Azure Functions V4

### ISSUE THREAD

**Issue by ajwhitehead88** [Azure/azure-functions-nodejs-library#279] opened 2024-06-26 14:26 UTC
_note: moved from https://github.com/Azure/azure-sdk-for-js/issues/30183_

- **Package Name**: `@azure/functions`
- **Package Version**: `4.5.0`
- **Operating system**: Linux
- **nodejs**
    - **version**: `20`

**Describe the bug**
When we push up a zip file into an storage blob and set `WEBSITE_RUN_FROM_PACKAGE` to be a URL to this blob as [described in the documentation](https://learn.microsoft.com/en-us/azure/azure-functions/run-functions-from-deployment-package#using-website_run_from_package--url) then we get no functions found. This is required for using a Dynamic Y1 plan.

However, if we push the _same_ zip using a normal Zip Deploy to a Basic plan with `WEBSITE_RUN_FROM_PACKAGE` set to `1` then we do see the functions.

If we downgrade the `@azure/functions` library and use a [v3 folder structure](https://learn.microsoft.com/en-us/azure/azure-functions/functions-reference-node?pivots=nodejs-model-v3#folder-structure) with a `host.json` at the root and a folder for each function containing a `function.json` file then we do see the functions with `WEBSITE_RUN_FROM_PACKAGE` set to a URL.

This appears to be a problem with Azure Functions v4.

**To Reproduce**
1. Create a super simple zip file containing only the `package.json` with a `main` of `./index.js`, `index.js` (with a http handler that returns 200) and the most basic `host.json`

* package.json
```
{
  "name": "functions-test",
  "version": "1.0.0",
  "main": "./index.js",
}
```
* host.json
```
{
  "version": "2.0",
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[4.0.0, 5.0.0)"
  }
}
```
* index.js
```
import { app } from '@azure/functions';

app.http('test', {
  methods: 'GET',
  handler: () => ({ status: 200 }),
});

```
2. Upload this to a storage blob
3. Create a function app with `WEBSITE_RUN_FROM_PACKAGE` to be a URL to the storage blob and `FUNCTIONS_NODE_BLOCK_ON_ENTRY_POINT_ERROR` to be `true`
4. Ensure the function app's identity has read access to the storage blob
5. Restart the function app

**Expected behavior**
Once restarted we should see a function called `test` in the interface and hitting the /api/test URL would give us a 200 response. In reality we see nothing and in the logs we get the following error:

> No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).

**Screenshots**
![343100551-f1fba7c1-f416-4dc9-9fdf-e9bc7849b683](https://github.com/Azure/azure-functions-nodejs-library/assets/341554/eef4b216-9744-4f13-9f44-bcd287346610)

**Additional context**
The reason we want to use this method over `WEBSITE_RUN_FROM_PACKAGE=1`  is so we can use the Dynamic Y1 tier in Azure Functions which has this value set to the ZIP URL as a requirement.

We don't want to downgrade our `@azure/functions` package as this is used elsewhere in our monorepo and would like to reduce the potential for package problems here as well.

**Comment by ejizba** [comment] 2024-06-26 17:24
Hi @ajwhitehead88 can you make sure your zip package has the "package.json" file included at the root? The v4 model reads the "main" field to know which files to load, so if that file is missing you might get "no functions found". In general, please check the contents of the zip package to make sure it matches the working version exactly. I suspect either a missing file or different folder structure is causing the issue here.

If that doesn't help, please follow these instructions to share your app info privately: https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately

**Comment by ajwhitehead88** [comment] 2024-06-26 18:37
Hi @ejizba - Yes that is correct. We have a `package.json` with the `"main"` field pointing to a single `index.js` with a simple v4 http handler. Also a basic `host.json`.

I'll set up a simple resource group now that replicates the issue and provide you the details.

**Comment by ajwhitehead88** [comment] 2024-06-27 08:45
Hi @ejizba - I have used the second method from that link as I don't get any functions visible to call.

**GUID:** 996f6286-ec34-437f-a1fd-415493222de9
**Region:** UK South
**UTC:** around 2024-06-27T08:44:37.603Z

Is this enough to get what you need?

**Comment by ajwhitehead88** [comment] 2024-07-03 10:18
I think we might be getting somewhere with it, it might be due to how `pnpm` is [creating a symlinked node_modules folder](https://pnpm.io/symlinked-node-modules-structure).

If we use normal `npm` to create the folder and ensure our filenames match the function names _(???)_ then it _appears_ to work as expected.

Will keep looking

**Comment by ejizba** [comment] 2024-07-15 17:47
@ajwhitehead88 sorry for the delay, were you able to get this figured out? I didn't look at your guid information, but your theory related to pnpm definitely sounds like it could be the cause.

**Comment by ajwhitehead88** [comment] 2024-07-21 11:57
@ejizba - No probs, we have worked around the `pnpm` issue using a small "hack" in our github action for now.

We `pnpm deploy` the package folder into it's own place and then uses `npm` to replace the `node_modules` folder which solves our symlinking issue. There is a potential second issue where the function name has to match the file name I believe which is a minor annoyance but nothing that stops the functions from working.

In our GitHub Action:
```
      - run: pnpm install --prefer-offline --frozen-lockfile

      - run: pnpm --filter package-to-deploy  build

      - run: pnpm --filter package-to-deploy deploy --prod /tmp/deploy

      # PNPM -> NPM fix to remove symlinks
      - run: |
          jq 'del(.devDependencies)' package.json > package.tmp
          mv package.tmp package.json
          rm -r node_modules
          npm i --omit=dev
        working-directory: /tmp/deploy
```

_Note: we remove devDependencies as there are unresolved workspace references to things like shared eslint/vitest/etc configs that work work unless in the full workspace_

We've had a call with some folks from Azure to iron out the last bits so think there might be some headway soon but otherwise we have working code at the moment so all good for now but would be nice to remove that extra `run` action in the future.

**Comment by ejizba** [comment] 2024-07-23 17:40
Glad you got everything figured out! Just curious, how are you actually deploying at the end of the day? I would say the best alternative to your existing workaround is to force your deployment mechanism to automatically copy symlinked files into the deployment package. For example, back when I worked on the VS Code extension we fixed this problem in VS Code [here](https://github.com/microsoft/vscode-azurefunctions/issues/1289). Depending on your deployment mechanism, you might have to file a new issue if they don't support this.

> There is a potential second issue where the function name has to match the file name I believe which is a minor annoyance but nothing that stops the functions from working.

This is the default behavior for the sake of cleanliness, but for the V4 model you can name your files whatever you want as long as they are included by the "main" field in your package.json.

I'm going to go ahead and close this issue. I think this is more of a deployment tooling issue and as mentioned above would recommend you follow up with your deployment mechanism if desired

**Closed as completed by ejizba** 2024-07-23 17:40 UTC

**Comment by ajwhitehead88** [comment] 2024-08-05 12:44
No problem, things are working now with the workarounds so think we are relatively clear and we can look at this further down the line on our side 👍 

We were deploying with GitHub Actions to then trigger a `pulumi` action. Doing things manually via the Azure portal caused the same problem so we ruled out both tools fairly early we believe but it is worth another look regardless!
