### ISSUE TITLE
app.<http_verb>() methods don't generate a unique id for the same route name but different verbs

### ISSUE THREAD

**Issue by sinedied** [Azure/azure-functions-nodejs-library#243] opened 2024-04-04 07:43 UTC
#### Repro steps

If you create a project and register two function using the same route but different verbs, you get the error `Error: Worker was unable to load entry point "xxx": a function with id "<route>" has already been registered`.

<img width="1058" alt="image" src="https://github.com/Azure/azure-functions-nodejs-library/assets/593151/6086277a-5d25-4e6a-983f-9a267a1e51f6">

Example:
```ts
// In functions/get-documents.ts
app.get('documents', { ... });

// In functions/post-documents.ts
app.post('documents', { ... });
```

Having both of these functions creates a conflict on the ID, despite the fact that they're using different verbs.
Workaround is to use:

```ts
app.http('get-documents', { route: 'documents', ... });

app.http('post-documents', { route: 'documents', ... });
```

#### Expected behavior

When using methods for HTTP verbs shortcuts, I would expect a unique id to be generated. This could be done easily by prefixing the verb to the route name when creating the id, ie `<verb>-<route>` so that the same route with different verbs like in my example do not generate a conflict.

#### Actual behavior

Currently, despite using different HTTP verbs, it seems that the generated id is only using the route, creating a conflict.

#### Known workarounds

Using `app.http()` instead of `app.<verb>()`

**Comment by ejizba** [comment] 2024-04-04 17:48
Hi @sinedied, yes this is a known issue, but has several workarounds. Closing as a duplicate of https://github.com/Azure/azure-functions-nodejs-library/issues/98

**Closed as not planned by ejizba** 2024-04-04 17:48 UTC
Labels: duplicate
